export type ClothingCategory = "eyes" | "hair" | "top" | "bottom" | "shoes"

export interface CatalogItem {
    id: string
    name: string
    category: ClothingCategory
    image: string // path to SVG in /sprites/
    maxSupply: number
    priceLamports: number // SOL price for launchpad minting (in lamports)
    priceBerry: number // Berry token price for store
    description: string
    zIndex: number // layering order for character editor
}

export const CATEGORY_LABELS: Record<ClothingCategory, string> = {
    eyes: "Eyes",
    hair: "Hair",
    top: "Tops",
    bottom: "Bottoms",
    shoes: "Shoes",
}

export const CATEGORY_Z_INDEX: Record<ClothingCategory, number> = {
    shoes: 1,
    bottom: 2,
    top: 3,
    eyes: 4,
    hair: 5,
}

export const CATALOG: CatalogItem[] = [
    // === EYES ===
    {
        id: "eyes-green-1",
        name: "Emerald Gaze I",
        category: "eyes",
        image: "/sprites/eyes-recolor-green-1.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 50,
        description: "Bright emerald eyes with a gentle sparkle",
        zIndex: 4,
    },
    {
        id: "eyes-green-2",
        name: "Emerald Gaze II",
        category: "eyes",
        image: "/sprites/eyes-recolor-green-2.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 50,
        description: "Deep emerald eyes with a curious look",
        zIndex: 4,
    },
    {
        id: "eyes-green-3",
        name: "Emerald Gaze III",
        category: "eyes",
        image: "/sprites/eyes-recolor-green-3.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 50,
        description: "Vivid emerald eyes with a dreamy shine",
        zIndex: 4,
    },
    {
        id: "eyes-green-4",
        name: "Emerald Gaze IV",
        category: "eyes",
        image: "/sprites/eyes-recolor-green-4.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 50,
        description: "Soft emerald eyes with a playful glint",
        zIndex: 4,
    },
    {
        id: "eyes-blue-1",
        name: "Ocean Eyes I",
        category: "eyes",
        image: "/sprites/eyes-recolor-blue-1.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 50,
        description: "Crystal ocean-blue eyes full of wonder",
        zIndex: 4,
    },
    {
        id: "eyes-blue-2",
        name: "Ocean Eyes II",
        category: "eyes",
        image: "/sprites/eyes-recolor-blue-2.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 50,
        description: "Sky-blue eyes with a calm expression",
        zIndex: 4,
    },
    {
        id: "eyes-blue-3",
        name: "Ocean Eyes III",
        category: "eyes",
        image: "/sprites/eyes-recolor-blue-3.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 50,
        description: "Ice-blue eyes that shimmer in the light",
        zIndex: 4,
    },
    {
        id: "eyes-blue-4",
        name: "Ocean Eyes IV",
        category: "eyes",
        image: "/sprites/eyes-recolor-blue-4.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 50,
        description: "Deep sapphire eyes with a bold look",
        zIndex: 4,
    },

    // === HAIR ===
    {
        id: "hair-1-1",
        name: "Cotton Candy Curls",
        category: "hair",
        image: "/sprites/hair-1-recol-1.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 100,
        description: "Fluffy curls in a pastel palette",
        zIndex: 5,
    },
    {
        id: "hair-1-2",
        name: "Strawberry Waves",
        category: "hair",
        image: "/sprites/hair-1-recol-2.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 100,
        description: "Wavy locks with strawberry tones",
        zIndex: 5,
    },
    {
        id: "hair-1-3",
        name: "Vanilla Dream",
        category: "hair",
        image: "/sprites/hair-1-recol-3.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 100,
        description: "Silky smooth hair in vanilla shades",
        zIndex: 5,
    },
    {
        id: "hair-2-1",
        name: "Midnight Flow",
        category: "hair",
        image: "/sprites/hair-2-recol-1.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 120,
        description: "Long flowing hair with a midnight sheen",
        zIndex: 5,
    },
    {
        id: "hair-2-2",
        name: "Sunset Cascade",
        category: "hair",
        image: "/sprites/hair-2-recol-2.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 120,
        description: "Cascading locks with sunset colors",
        zIndex: 5,
    },
    {
        id: "hair-2-3",
        name: "Aurora Borealis",
        category: "hair",
        image: "/sprites/hair-2-recol-3.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 120,
        description: "Shimmering hair in aurora hues",
        zIndex: 5,
    },

    // === TOPS ===
    {
        id: "hoodie-pastel-1",
        name: "Berry Breeze Hoodie",
        category: "top",
        image: "/sprites/hoodie-pastel-1.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 150,
        description: "A cozy hoodie in pastel berry tones",
        zIndex: 3,
    },
    {
        id: "hoodie-pastel-2",
        name: "Cloud Nine Hoodie",
        category: "top",
        image: "/sprites/hoodie-pastel-2.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 150,
        description: "Soft hoodie inspired by fluffy clouds",
        zIndex: 3,
    },
    {
        id: "hoodie-pastel-3",
        name: "Lavender Mist Hoodie",
        category: "top",
        image: "/sprites/hoodie-pastel-3.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 150,
        description: "Dreamy hoodie with lavender hues",
        zIndex: 3,
    },
    {
        id: "shirt-green",
        name: "Minty Fresh Tee",
        category: "top",
        image: "/sprites/shirt-green.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 80,
        description: "A fresh green tee for casual vibes",
        zIndex: 3,
    },
    {
        id: "shirt-lilac",
        name: "Lilac Bloom Tee",
        category: "top",
        image: "/sprites/shirt-lilac.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 80,
        description: "A soft lilac tee that blooms with style",
        zIndex: 3,
    },
    {
        id: "shirt-pink",
        name: "Pink Petal Tee",
        category: "top",
        image: "/sprites/shirt-pink.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 80,
        description: "A cute pink tee with petal-soft comfort",
        zIndex: 3,
    },
    {
        id: "shirt-yellow",
        name: "Sunshine Tee",
        category: "top",
        image: "/sprites/shirt-yellow.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 80,
        description: "Spread sunshine with this yellow tee",
        zIndex: 3,
    },

    // === BOTTOMS ===
    {
        id: "pants-1",
        name: "Berry Joggers",
        category: "bottom",
        image: "/sprites/pants-recol-1.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 100,
        description: "Comfortable joggers in berry tones",
        zIndex: 2,
    },
    {
        id: "pants-2",
        name: "Cloud Joggers",
        category: "bottom",
        image: "/sprites/pants-recol-2.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 100,
        description: "Light joggers with cloud-soft fabric",
        zIndex: 2,
    },
    {
        id: "pants-3",
        name: "Twilight Joggers",
        category: "bottom",
        image: "/sprites/pants-recol-3.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 100,
        description: "Joggers inspired by twilight hues",
        zIndex: 2,
    },
    {
        id: "skirt-blue",
        name: "Azure Skirt",
        category: "bottom",
        image: "/sprites/skirt-blue-2.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 120,
        description: "A flowy azure skirt for twirling",
        zIndex: 2,
    },
    {
        id: "skirt-green",
        name: "Meadow Skirt",
        category: "bottom",
        image: "/sprites/skirt-green-1.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 120,
        description: "A fresh meadow-green skirt",
        zIndex: 2,
    },
    {
        id: "skirt-lilac",
        name: "Wisteria Skirt",
        category: "bottom",
        image: "/sprites/skirt-lilac-2.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 120,
        description: "A graceful skirt in wisteria lilac",
        zIndex: 2,
    },

    // === SHOES ===
    {
        id: "shoes-1-blue",
        name: "Sky High Sneakers",
        category: "shoes",
        image: "/sprites/shoes-1-blue.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 80,
        description: "Blue sneakers that reach for the sky",
        zIndex: 1,
    },
    {
        id: "shoes-1-lilac",
        name: "Lavender Kicks",
        category: "shoes",
        image: "/sprites/shoes-1-lilac.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 80,
        description: "Lilac sneakers with a dreamy vibe",
        zIndex: 1,
    },
    {
        id: "shoes-2-green",
        name: "Forest Walkers",
        category: "shoes",
        image: "/sprites/shoes-2-green.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 90,
        description: "Green shoes for forest adventures",
        zIndex: 1,
    },
    {
        id: "shoes-2-lilac",
        name: "Lilac Steppers",
        category: "shoes",
        image: "/sprites/shoes-2-lilac.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 90,
        description: "Light lilac shoes for daily style",
        zIndex: 1,
    },
    {
        id: "shoes-2-pink",
        name: "Rosy Runners",
        category: "shoes",
        image: "/sprites/shoes-2-pink.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 90,
        description: "Pink shoes bursting with energy",
        zIndex: 1,
    },
    {
        id: "shoes-pink-1",
        name: "Bubblegum Boots",
        category: "shoes",
        image: "/sprites/shoes-pink-1.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 100,
        description: "Bold bubblegum-pink boots",
        zIndex: 1,
    },
    {
        id: "shoes-yellow-1",
        name: "Sunflower Stompers",
        category: "shoes",
        image: "/sprites/shoes-yellow-1.svg",
        maxSupply: 500,
        priceLamports: 0,
        priceBerry: 100,
        description: "Sunny yellow boots for making a statement",
        zIndex: 1,
    },
]

export function getCatalogByCategory(category: ClothingCategory): CatalogItem[] {
    return CATALOG.filter((item) => item.category === category)
}

export function getCatalogItem(id: string): CatalogItem | undefined {
    return CATALOG.find((item) => item.id === id)
}
